import assert from "node:assert/strict";
import test from "node:test";
import { validateProductionEnv } from "../src/config/env.js";
import { JsonStructuredLogger, sanitizeLogFields } from "../src/observability/logger.js";
import { MetricsRegistry } from "../src/observability/metrics.js";
import { contentHash, buildPendingQueue, verifyApproval, type ApprovalRecord, type ReviewerAuthorization } from "../src/review/approvals.js";
import { verifyRollbackPlan } from "../src/ops/deployment.js";

const validEnv={NODE_ENV:"production",PORT:"3000",DEPLOYMENT_TARGET:"production",RELEASE_ID:"release-1",ALLOWED_ORIGINS:"https://app.example.com",DATABASE_URL:"postgresql://user:password@db.example.com/nutriguard",QDRANT_URL:"https://qdrant.example.com",QDRANT_COLLECTION:"approved",EMBEDDING_BASE_URL:"https://embed.example.com/v1",EMBEDDING_API_KEY:"secret-key-value-123",EMBEDDING_MODEL:"reviewed-model",RETRIEVAL_CORPUS_ID:"corpus-1",NUTRIGUARD_RELEASE_EVIDENCE:"/run/secrets/evidence.json",METRICS_TOKEN:"a-very-long-metrics-token-value"}; // secret-scan: allow-test

test("production config is strict, HTTPS-only and never echoes secrets",()=>{assert.equal(validateProductionEnv(validEnv).ok,true);const secret="DONT-LEAK-THIS-PASSWORD";const invalid=validateProductionEnv({...validEnv,DATABASE_URL:secret,EMBEDDING_API_KEY:secret,METRICS_TOKEN:secret,QDRANT_URL:"http://localhost:6333"});assert.equal(invalid.ok,false);assert.equal(JSON.stringify(invalid).includes(secret),false);}); // secret-scan: allow-test
test("production CORS stores canonical browser origins without trailing slashes",()=>{const result=validateProductionEnv({...validEnv,ALLOWED_ORIGINS:"https://nutri-guard-frontend.vercel.app/"});assert.equal(result.ok,true);if(result.ok)assert.deepEqual(result.value.allowedOrigins,["https://nutri-guard-frontend.vercel.app"]);});
test("structured logs redact raw questions and credentials",()=>{const fields=sanitizeLogFields({route:"/api/v1/chat",message:"my medical question",apiKey:"secret",status:200});assert.equal(fields.message,"[REDACTED]");assert.equal(fields.apiKey,"[REDACTED]");const lines:string[]=[];new JsonStructuredLogger((line)=>lines.push(line)).log("info","request",fields);assert.equal(lines.join("").includes("my medical question"),false);});
test("metrics permit bounded operational labels and reject PII-like labels",()=>{const metrics=new MetricsRegistry();metrics.increment("nutriguard_http_requests_total",{route:"/ready",status:"200"});assert.match(metrics.render(),/status="200"/);assert.throws(()=>metrics.increment("bad",{user_email:"person@example.com"}));});
test("approval content hashes are deterministic and tampering fails closed",()=>{const subject={b:2,a:1};assert.equal(contentHash(subject),contentHash({a:1,b:2}));const authorization:ReviewerAuthorization={id:"AUT-0123456789ABCDEF",reviewerId:"reviewer-1",reviewerRole:"data_owner",qualification:"authorized data owner",subjectType:"recipe",subjectKeyPrefix:"R",validFrom:"2026-01-01",validUntil:null,revokedAt:null,authorizationEvidenceReference:"AUTH-EVID-1",authorizedBy:"governance-owner"};const record:ApprovalRecord={schemaVersion:"1.0",id:"APR-0123456789ABCDEF",subjectType:"recipe",subjectKey:"R1",contentSha256:contentHash(subject),decision:"approved",reviewerId:"reviewer-1",reviewerRole:"data_owner",authorizationId:authorization.id,reviewedAt:"2026-08-09T10:00:00+03:00",evidenceReference:"EVID-1",rationale:"Reviewed against source",supersedesId:null};assert.deepEqual(verifyApproval(record,subject,"data_owner",authorization),[]);assert.ok(verifyApproval(record,{a:9},"data_owner",authorization).includes("content_hash_mismatch"));assert.ok(verifyApproval(record,subject,"release_owner",authorization).includes("reviewer_role_not_authorized"));assert.ok(verifyApproval(record,subject,"data_owner").includes("reviewer_authorization_missing_or_mismatched"));assert.ok(verifyApproval(record,subject,"data_owner",{...authorization,revokedAt:"2026-08-01T00:00:00Z"}).includes("review_outside_authorized_scope_or_date"));});
test("queue generation is deterministic and always pending",()=>{const a=buildPendingQueue("source_license","SRC-1",{license:"pending"},"data_owner");const b=buildPendingQueue("source_license","SRC-1",{license:"pending"},"data_owner");assert.deepEqual(a,b);assert.equal(a.status,"pending");});
test("rollback requires immutable digest, compatibility and owner approval",()=>{assert.ok(verifyRollbackPlan({}).length>=3);assert.deepEqual(verifyRollbackPlan({previousReleaseId:"r1",previousImageDigest:`sha256:${"a".repeat(64)}`,databaseBackwardCompatible:true,rollbackOwnerApproved:true}),[]);});
