export function renderChatPage(nonce: string): string { return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>NutriGuard Egypt</title>
  <style nonce="${nonce}">
    :root{color-scheme:light;--ink:#102f35;--muted:#587076;--paper:#f6f1e5;--card:#fffdf8;--green:#176b58;--lime:#d9e6a3;--sand:#d6b66f;--red:#9d3d38;--line:#d8d3c7;--shadow:0 18px 50px rgba(20,51,55,.12)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% 8%,#e8efcf 0,transparent 25%),linear-gradient(150deg,#f8f4e9,#eef3ed);font-family:"Segoe UI",Tahoma,Arial,sans-serif;color:var(--ink)}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.22;background:repeating-linear-gradient(90deg,transparent 0 47px,rgba(23,107,88,.08) 48px)}
    .shell{position:relative;max-width:1120px;margin:auto;padding:28px;display:grid;grid-template-columns:310px minmax(0,1fr);gap:22px;min-height:100vh}
    .brand,.chat{background:rgba(255,253,248,.92);border:1px solid rgba(16,47,53,.12);box-shadow:var(--shadow)}.brand{border-radius:30px;padding:28px;display:flex;flex-direction:column}.mark{width:58px;height:58px;border-radius:18px;background:var(--green);color:white;display:grid;place-items:center;font-weight:800;font-size:24px;transform:rotate(-4deg)}
    h1{font-size:35px;line-height:1;margin:24px 0 10px;letter-spacing:-1px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:1.6px;color:var(--green)}.intro{line-height:1.8;color:var(--muted)}
    .status{margin-top:18px;border-top:1px solid var(--line);padding-top:18px;display:grid;gap:10px}.pill{display:flex;align-items:center;gap:8px;font-size:13px}.dot{width:9px;height:9px;background:#399877;border-radius:50%;box-shadow:0 0 0 5px #dceee7}.demo{margin-top:auto;padding:15px;border-radius:18px;background:#fff4d8;border:1px solid #ead29d;font-size:12px;line-height:1.7}
    .chat{border-radius:30px;overflow:hidden;display:flex;flex-direction:column;min-height:calc(100vh - 56px)}.top{padding:20px 24px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.top strong{font-size:16px}.session{font-size:12px;color:var(--muted)}
    #messages{flex:1;overflow:auto;padding:28px;display:flex;flex-direction:column;gap:16px}.message{max-width:82%;padding:15px 17px;border-radius:20px;line-height:1.75;white-space:pre-wrap}.user{align-self:flex-start;background:var(--green);color:white;border-bottom-left-radius:6px}.assistant{align-self:flex-end;background:#f1eee5;border:1px solid var(--line);border-bottom-right-radius:6px}.meta{font-size:11px;color:var(--muted);margin-top:8px}.sources{margin-top:10px;padding-top:9px;border-top:1px dashed #c4c0b7;font-size:12px}
    .welcome{margin:auto;max-width:560px;text-align:center}.welcome h2{font-size:30px;margin:0 0 10px}.welcome p{color:var(--muted);line-height:1.8}.suggestions{display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin-top:20px}.suggestions button{border:1px solid var(--line);background:var(--card);padding:9px 12px;border-radius:999px;color:var(--ink);cursor:pointer}
    form{padding:18px;border-top:1px solid var(--line);display:flex;gap:10px;background:rgba(255,255,255,.7)}textarea{flex:1;resize:none;min-height:54px;max-height:150px;border:1px solid #b9c5c1;border-radius:18px;padding:14px 16px;font:inherit;outline:none;background:white}textarea:focus{border-color:var(--green);box-shadow:0 0 0 3px rgba(23,107,88,.13)}button[type=submit]{border:0;border-radius:18px;background:var(--green);color:white;font-weight:800;padding:0 23px;cursor:pointer}button:disabled{opacity:.55;cursor:wait}.error{color:var(--red)}
    @media(max-width:780px){.shell{height:100vh;display:flex;flex-direction:column;overflow:hidden;padding:10px}.brand{flex:0 0 auto;border-radius:22px 22px 0 0;padding:16px}.brand h1,.brand .intro,.brand .status{display:none}.mark{width:40px;height:40px;font-size:18px;transform:none}.eyebrow{direction:ltr;text-align:right}.demo{display:block;min-height:64px;margin:10px 0 0;padding:10px 12px;color:var(--ink)}.chat{flex:1;min-height:0;border-radius:0 0 22px 22px}#messages{min-height:0;padding:16px}.message{max-width:92%}.top{padding:15px 18px}form{flex:0 0 auto;padding:11px}button[type=submit]{padding:0 16px}}
    @media(prefers-reduced-motion:no-preference){.message{animation:rise .22s ease-out}@keyframes rise{from{opacity:0;transform:translateY(8px)}}}
  </style>
</head>
<body><main class="shell"><aside class="brand"><div class="mark" aria-hidden="true">NG</div><div class="eyebrow">NUTRIGUARD · EGYPT</div><h1>الأكل المصري،<br>بأرقام موثّقة.</h1><p class="intro">مساعد تغذية محدود النطاق، بيفصل الحساب عن الكلام ويحافظ على المصدر مع كل نتيجة.</p><div class="status"><div class="pill"><span class="dot"></span>الخدمة جاهزة</div><div class="pill">الأرقام من حاسبة حتمية فقط</div><div class="pill">مش بديل للطبيب</div></div><div class="demo"><strong>وضع تجريبي اصطناعي</strong><br>البيانات هنا للاختبار فقط ومش صالحة لقرار غذائي حقيقي.</div></aside><section class="chat" aria-label="محادثة NutriGuard"><header class="top"><strong>اسأل عن أكلة مصرية</strong><span class="session" id="sessionLabel"></span></header><div id="messages" aria-live="polite"><div class="welcome" id="welcome"><h2>أهلاً بيك 👋</h2><p>اسأل عن صوديوم وصفة، قارن أكلتين على نفس الأساس، أو اسأل عن الهرم الغذائي.</p><div class="suggestions"><button data-q="الصوديوم في الكشري لكل 100 جرام">صوديوم الكشري</button><button data-q="قارن بين الكشري والملوخية لكل 100 جرام">قارن وصفتين</button><button data-q="إيه هو الهرم الغذائي؟">الهرم الغذائي</button></div></div></div><form id="chatForm"><label for="message" hidden>اكتب سؤالك</label><textarea id="message" maxlength="2000" required placeholder="اكتب سؤالك هنا…" rows="1"></textarea><button type="submit">ابعت</button></form></section></main>
<script nonce="${nonce}">
const sessionId=crypto.randomUUID(),messages=document.querySelector('#messages'),form=document.querySelector('#chatForm'),input=document.querySelector('#message'),send=form.querySelector('button');document.querySelector('#sessionLabel').textContent='جلسة '+sessionId.slice(0,8);
function bubble(text,kind,meta='',sources=[]){document.querySelector('#welcome')?.remove();const box=document.createElement('article');box.className='message '+kind;box.textContent=text;if(meta){const m=document.createElement('div');m.className='meta';m.textContent=meta;box.append(m)}if(sources.length){const s=document.createElement('div');s.className='sources';s.textContent='المصادر: '+sources.map(x=>x.title||x.sourceId).join(' · ');box.append(s)}messages.append(box);messages.scrollTop=messages.scrollHeight}
async function ask(text){bubble(text,'user');send.disabled=true;input.disabled=true;try{const res=await fetch('/api/v1/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,language:'ar-EG'})});const body=await res.json();if(!res.ok)throw new Error(body.error?.message||'الخدمة مش متاحة');bubble(body.result.message,'assistant',body.result.status+' · prompt '+body.result.promptVersion,body.result.provenance||[])}catch(err){bubble('حصلت مشكلة: '+err.message,'assistant error')}finally{send.disabled=false;input.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(text){input.value='';ask(text)}});document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.q)));input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
</script></body></html>`; }
