export function renderChatPage(nonce: string): string {
  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#f7f8f6">
  <title>NutriGuard Egypt</title>
  <style nonce="${nonce}">
    :root{color-scheme:light;--bg:#f7f8f6;--sidebar:#f1f3f0;--surface:#fff;--ink:#202521;--muted:#69716b;--line:#e1e5e1;--green:#176b58;--green-dark:#105346;--green-soft:#e4f1ec;--danger:#a3453e;--danger-soft:#fbecea;--shadow:0 8px 30px rgba(29,45,37,.09);--focus:0 0 0 3px rgba(23,107,88,.2)}
    *{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--ink);font-family:Tahoma,"Segoe UI",sans-serif;line-height:1.65}button,textarea{font:inherit;color:inherit}button{cursor:pointer}button:focus-visible,textarea:focus-visible,a:focus-visible,summary:focus-visible{outline:0;box-shadow:var(--focus)}[hidden]{display:none!important}
    .app{height:100dvh;display:grid;grid-template-columns:minmax(0,1fr) 252px;overflow:hidden;direction:ltr}.sidebar{grid-column:2;grid-row:1;direction:rtl;background:var(--sidebar);border-left:1px solid var(--line);padding:15px 12px;display:flex;flex-direction:column;min-height:0}.main{grid-column:1;grid-row:1;direction:rtl;min-width:0;min-height:0;display:grid;grid-template-rows:56px minmax(0,1fr) auto;background:var(--surface)}
    .brand{display:flex;align-items:center;gap:10px;padding:6px 7px 14px}.logo{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--green);color:#fff;font-weight:800;font-size:12px;box-shadow:0 5px 12px rgba(23,107,88,.2)}.brand-copy{display:grid;line-height:1.2}.brand-copy strong{font-size:14px}.brand-copy span{margin-top:3px;font-size:11px;color:var(--muted)}
    .new-chat{width:100%;height:42px;border:1px solid var(--line);border-radius:10px;background:var(--surface);display:flex;align-items:center;justify-content:space-between;padding:0 13px;font-size:12px;font-weight:700;transition:border-color .18s,box-shadow .18s}.new-chat:hover{border-color:#bdc8c1;box-shadow:0 3px 12px rgba(29,45,37,.06)}.plus{font-size:19px;color:var(--green);font-weight:400}
    .nav-label{margin:21px 9px 8px;font-size:11px;color:var(--muted)}.quick-list{display:grid;gap:3px}.quick{border:0;background:transparent;border-radius:8px;padding:9px 10px;text-align:right;color:#47504a;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quick:hover{background:#e6e9e5;color:var(--ink)}
    .topbar{border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;background:rgba(255,255,255,.94)}.top-title{font-size:13px;font-weight:700}.top-hint{font-size:10px;color:var(--muted)}.mobile-brand{display:none;align-items:center;gap:8px;font-size:12px;font-weight:800}.mobile-brand .logo{width:29px;height:29px;border-radius:9px;font-size:10px}
    #messages{min-height:0;overflow-y:auto;padding:32px max(24px,calc((100% - 780px)/2));display:flex;flex-direction:column;gap:22px;scrollbar-color:#cbd1cc transparent;scroll-behavior:smooth}.welcome{margin:auto;width:min(660px,100%);text-align:center;padding-bottom:5vh}.welcome-logo{width:52px;height:52px;margin:0 auto 17px;border-radius:16px;display:grid;place-items:center;background:var(--green);color:#fff;font-weight:800;box-shadow:0 9px 24px rgba(23,107,88,.17)}.welcome h1{margin:0;font-size:27px;line-height:1.4;letter-spacing:-.45px}.welcome>p{margin:8px auto 24px;color:var(--muted);font-size:13px}.starters{display:grid;grid-template-columns:1fr 1fr;gap:9px;text-align:right}.starter{min-height:64px;padding:11px 13px;border:1px solid var(--line);border-radius:12px;background:var(--surface);font-size:11px;line-height:1.6;transition:border-color .18s,box-shadow .18s,transform .18s}.starter strong{display:block;font-size:11px;margin-bottom:2px}.starter span{color:var(--muted);font-size:10px}.starter:hover{border-color:#b8c6bf;box-shadow:0 5px 18px rgba(29,45,37,.07);transform:translateY(-1px)}
    .message{width:100%;animation:arrive .2s ease-out}.message-inner{width:min(720px,100%);margin:auto;display:grid;grid-template-columns:32px minmax(0,1fr);gap:13px;align-items:start}.avatar{width:30px;height:30px;border-radius:9px;display:grid;place-items:center;font-size:10px;font-weight:800}.user .avatar{background:#ecefec;color:#4c554f}.assistant .avatar{background:var(--green);color:#fff}.content{min-width:0;padding-top:2px}.answer{white-space:pre-wrap;font-size:13px;line-height:1.85}.error .answer{padding:11px 13px;border-radius:10px;background:var(--danger-soft);color:#743a35}
    .nutrition-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:11px}.nutrition-value{min-width:118px;padding:9px 11px;border-radius:9px;background:var(--green-soft)}.nutrition-value strong{display:block;color:var(--green-dark);font-size:18px;line-height:1.2}.nutrition-value span{font-size:9px;color:#52675e}
    .comparison-wrap{overflow-x:auto;margin-top:12px;border:1px solid var(--line);border-radius:10px}.comparison{width:100%;border-collapse:collapse;font-size:10px;min-width:460px}.comparison th,.comparison td{padding:8px 9px;border-bottom:1px solid var(--line);text-align:right}.comparison th{background:#f5f7f5;color:#4b554f}.comparison td:not(:first-child){direction:ltr;text-align:center}.comparison tr:last-child td{border-bottom:0}.unknown{color:var(--muted)}
    .details{margin-top:10px;border-top:1px solid var(--line)}.details summary{width:max-content;max-width:100%;list-style:none;padding:9px 2px 3px;cursor:pointer;color:var(--muted);font-size:11px}.details summary::-webkit-details-marker{display:none}.details summary:after{content:"  +";color:var(--green)}.details[open] summary:after{content:"  −"}.details-body{padding:6px 0 2px;display:grid;gap:8px}.source-item{padding:8px 10px;border-radius:8px;background:#f5f7f5}.source-item strong{display:block;font-size:11px}.source-item p{margin:3px 0 0;color:var(--muted);font-size:10px;line-height:1.65}.source-links{display:flex;flex-wrap:wrap;gap:5px}.source-chip{display:inline-flex;border:1px solid var(--line);border-radius:7px;padding:4px 7px;color:var(--muted);font-size:10px;text-decoration:none}.source-chip.link:hover{color:var(--green-dark);border-color:#b8c6bf}
    .typing .answer{display:flex;align-items:center;gap:5px;min-height:28px}.typing-dot{width:5px;height:5px;border-radius:50%;background:var(--green);animation:pulse 1s infinite}.typing-dot:nth-child(2){animation-delay:.15s}.typing-dot:nth-child(3){animation-delay:.3s}.typing-label{font-size:10px;color:var(--muted);margin-right:3px}
    .composer-zone{padding:10px max(20px,calc((100% - 780px)/2)) max(12px,env(safe-area-inset-bottom));background:linear-gradient(to top,#fff 78%,rgba(255,255,255,0))}.composer{display:grid;grid-template-columns:minmax(0,1fr) 42px;align-items:end;border:1px solid #cdd3ce;border-radius:18px;background:var(--surface);padding:5px 6px 5px 7px;box-shadow:var(--shadow);transition:border-color .18s,box-shadow .18s}.composer:focus-within{border-color:#8eaaa0;box-shadow:0 9px 32px rgba(29,45,37,.11),var(--focus)}textarea{width:100%;min-height:44px;max-height:130px;border:0;outline:0;resize:none;background:transparent;padding:11px 12px;font-size:13px;line-height:1.65}textarea::placeholder{color:#8b928d}.send{width:38px;height:38px;margin-bottom:2px;border:0;border-radius:12px;background:var(--green);color:#fff;display:grid;place-items:center;font-size:18px;line-height:1;transition:background .18s,transform .18s}.send:hover{background:var(--green-dark)}.send:active{transform:scale(.97)}.send:disabled{opacity:.45;cursor:not-allowed}.helper{text-align:center;margin:6px 6px 0;color:var(--muted);font-size:10px}.count{margin-inline-start:8px}.count.warn{color:var(--danger);font-weight:800}
    @keyframes arrive{from{opacity:0;transform:translateY(5px)}}@keyframes pulse{0%,70%,100%{opacity:.25;transform:translateY(0)}35%{opacity:1;transform:translateY(-2px)}}
    @media(max-width:760px){.app{display:block}.sidebar{display:none}.main{height:100dvh;grid-template-rows:52px minmax(0,1fr) auto}.topbar{padding:0 14px}.top-title,.top-hint{display:none}.mobile-brand{display:flex}.demo-label{font-size:9px;color:var(--muted)}#messages{padding:22px 14px}.welcome{padding:0 4px 3vh}.welcome-logo{width:46px;height:46px;border-radius:14px;margin-bottom:14px}.welcome h1{font-size:23px}.welcome>p{font-size:11px;margin-bottom:18px}.starters{grid-template-columns:1fr}.starter{min-height:auto}.message-inner{grid-template-columns:29px minmax(0,1fr);gap:10px}.avatar{width:27px;height:27px;border-radius:8px}.answer{font-size:12px}.composer-zone{padding:8px 9px max(9px,env(safe-area-inset-bottom))}.composer{border-radius:16px}.helper{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
    @media(max-width:380px){.demo-label{max-width:145px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.starter:nth-child(n+4){display:none}.helper{font-size:8px}.details summary,.source-item strong{font-size:10px}.source-item p,.source-chip{font-size:9px}}
    @media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
  </style>
</head>
<body>
  <main class="app">
    <aside class="sidebar" aria-label="القائمة الجانبية">
      <div class="brand"><div class="logo" aria-hidden="true">NG</div><div class="brand-copy"><strong>NutriGuard</strong><span>مساعد الأكل المصري</span></div></div>
      <button class="new-chat" id="newChat" type="button"><span>محادثة جديدة</span><span class="plus" aria-hidden="true">＋</span></button>
      <div class="nav-label">جرّب سؤالًا</div>
      <nav class="quick-list" aria-label="أسئلة مقترحة"><button class="quick" type="button" data-q="اقترح لي وجبة فطار مصرية">اقتراح وجبة فطار</button><button class="quick" type="button" data-q="كام سعر حراري في الكشري؟">سعرات الكشري</button><button class="quick" type="button" data-q="احسب سعرات 150 جرام أرز + 100 جرام صدور فراخ + 10 جرام زيت زيتون">احسب مكونات وجبتي</button><button class="quick" type="button" data-q="اديني نصائح عامة لأكل صحي">نصائح غذائية عامة</button></nav>
    </aside>
    <section class="main" aria-label="محادثة NutriGuard">
      <header class="topbar"><div class="mobile-brand"><div class="logo" aria-hidden="true">NG</div><span>NutriGuard</span></div><span class="top-title">مساعد التغذية للأكل المصري</span><span class="top-hint">اسأل بالعربية أو الإنجليزية</span><span class="demo-label">نسخة مشروع التخرج · بيانات تقديرية</span></header>
      <div id="messages" aria-live="polite" aria-busy="false">
        <section class="welcome" id="welcome"><div class="welcome-logo" aria-hidden="true">NG</div><h1>أهلًا، أنا NutriGuard</h1><p>أقترح وجبات مصرية، أحسب السعرات، وأقدّم نصائح غذائية عامة.</p><div class="starters"><button class="starter" type="button" data-q="اقترح لي وجبة فطار مصرية"><strong>اقترح وجبة فطار</strong><span>اختيارات مصرية من قاعدة المشروع</span></button><button class="starter" type="button" data-q="كام سعر حراري في الكشري؟"><strong>سعرات أكلة مصرية</strong><span>للحصة ولكل 100 جرام</span></button><button class="starter" type="button" data-q="احسب سعرات 150 جرام أرز + 100 جرام صدور فراخ + 10 جرام زيت زيتون"><strong>احسب مكونات وجبتي</strong><span>اكتب كل مكوّن ووزنه بالجرام</span></button><button class="starter" type="button" data-q="اديني نصائح عامة لأكل صحي"><strong>نصائح غذائية عامة</strong><span>معلومات عامة وليست نصيحة طبية</span></button></div></section>
      </div>
      <div class="composer-zone"><form id="chatForm"><label for="message" hidden>اكتب سؤالك عن الأكل المصري</label><div class="composer"><textarea id="message" maxlength="2000" required rows="1" placeholder="اسأل عن أكلة مصرية…"></textarea><button class="send" type="submit" aria-label="إرسال السؤال">↑</button></div><div class="helper">قد تحتوي الإجابات على أخطاء، راجع المعلومات المهمة.<span class="count" id="charCount">0 / 2000</span></div></form></div>
    </section>
  </main>
  <script nonce="${nonce}">
    const messages=document.querySelector('#messages');
    const form=document.querySelector('#chatForm');
    const input=document.querySelector('#message');
    const send=form.querySelector('.send');
    const count=document.querySelector('#charCount');
    let pending=false;
    let conversationContext=null;

    function safeUrl(value){try{const url=new URL(value);return url.protocol==='http:'||url.protocol==='https:'?url:null}catch{return null}}
    function text(value,fallback='—'){return typeof value==='string'&&value.trim()?value.trim():fallback}
    function number(value){return typeof value==='number'&&Number.isFinite(value)?value:null}
    function append(parent,tag,className,content){const node=document.createElement(tag);if(className)node.className=className;if(content!==undefined)node.textContent=content;parent.append(node);return node}
    function basis(value){return ({per_100g:'لكل 100 جرام',per_serving:'لكل حصة',full_recipe:'للوصفة كاملة'})[value]||text(value)}
    function localize(value){return text(value,'وصل رد بدون نص قابل للعرض.').replaceAll('per_100g','لكل 100 جرام').replaceAll('per_serving','لكل حصة').replaceAll('full_recipe','للوصفة كاملة')}
    function nutrient(value){return ({calories:'السعرات',protein:'البروتين',carbohydrate:'الكربوهيدرات',total_fat:'الدهون',saturated_fat:'الدهون المشبعة',fiber:'الألياف',sugar:'السكر',sodium:'الصوديوم'})[value]||value}
    function internalLabel(value){return !value||/(?:DEMO|GRADUATION|UNREVIEWED|EGY[-_]RCP|^[A-Z0-9_-]{12,}$)/iu.test(value)}
    function friendlyLabel(value,index,kind='مصدر'){const candidate=text(value,'');return internalLabel(candidate)?kind+' '+new Intl.NumberFormat('ar-EG').format(index+1):candidate}
    function addAvatar(parent,kind){append(parent,'div','avatar',kind==='user'?'أنت':'NG')}
    function addCalories(parent,data){const values=[];const total=number(data?.totalCaloriesKcal);const serving=number(data?.caloriesPerServingKcal);const per100=number(data?.caloriesPer100gKcal);if(total!==null)values.push([total,data?.calculationType==='ingredient_weights'?'إجمالي الوجبة':'إجمالي الوصفة']);if(serving!==null)values.push([serving,'للحصة']);if(per100!==null)values.push([per100,'لكل 100 جرام']);if(!values.length)return;const row=append(parent,'div','nutrition-row');values.forEach(([value,label])=>{const item=append(row,'div','nutrition-value');append(item,'strong','',new Intl.NumberFormat('ar-EG',{maximumFractionDigits:1}).format(value)+' سعر');append(item,'span','',label)})}
    function addSodium(parent,data){const value=number(data?.sodiumMg);if(value===null)return;const row=append(parent,'div','nutrition-row');const item=append(row,'div','nutrition-value');append(item,'strong','',new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(value)+' مجم');append(item,'span','','الصوديوم '+basis(data?.basis))}
    function addComparison(parent,data){if(!data?.nutrients||typeof data.nutrients!=='object')return;const entries=Object.entries(data.nutrients).filter(([,value])=>value&&typeof value==='object');if(!entries.length)return;const wrap=append(parent,'div','comparison-wrap');const table=append(wrap,'table','comparison');const head=append(table,'thead');const hr=append(head,'tr');['العنصر','الوصفة الأولى','الوصفة الثانية','الفرق'].forEach(label=>append(hr,'th','',label));const body=append(table,'tbody');entries.forEach(([key,value])=>{const row=append(body,'tr');append(row,'td','',nutrient(key));['first','second','difference'].forEach(field=>{const amount=number(value[field]);append(row,'td',amount===null?'unknown':'',amount===null?'غير معروف':String(Math.round(amount*100)/100)+' '+text(value.unit,''))})})}
    function addDetails(parent,data,sources,documentIds){const passages=Array.isArray(data?.passages)?data.passages:[];const provenance=Array.isArray(sources)?sources:[];const ids=Array.isArray(documentIds)?documentIds:[];if(!passages.length&&!provenance.length&&!ids.length)return;const details=append(parent,'details','details');append(details,'summary','','المصادر والتفاصيل');const body=append(details,'div','details-body');passages.slice(0,4).forEach((passage,index)=>{const item=append(body,'article','source-item');append(item,'strong','',friendlyLabel(passage?.title,index,'وثيقة مرتبطة'));append(item,'p','',text(passage?.text,'لا يوجد مقتطف متاح.').slice(0,360))});if(!passages.length&&ids.length){ids.slice(0,4).forEach((_,index)=>{const item=append(body,'article','source-item');append(item,'strong','',friendlyLabel('',index,'دليل مرتبط'))})}if(provenance.length){const links=append(body,'div','source-links');provenance.slice(0,8).forEach((source,index)=>{const url=safeUrl(source?.url);const node=document.createElement(url?'a':'span');node.className='source-chip'+(url?' link':'');const candidate=text(source?.title,'');node.textContent=url?.hostname.endsWith('who.int')&&internalLabel(candidate)?'منظمة الصحة العالمية':friendlyLabel(candidate,index,'مصدر الوصفة');if(url){node.href=url.href;node.target='_blank';node.rel='noopener noreferrer'}links.append(node)})}}
    function addUser(value){document.querySelector('#welcome')?.remove();const article=append(messages,'article','message user');const inner=append(article,'div','message-inner');addAvatar(inner,'user');const content=append(inner,'div','content');append(content,'div','answer',value);messages.append(article);messages.scrollTop=messages.scrollHeight}
    function addAssistant(result){const article=append(messages,'article','message assistant');const inner=append(article,'div','message-inner');addAvatar(inner,'assistant');const content=append(inner,'div','content');append(content,'div','answer',localize(result?.message));const data=result?.data&&typeof result.data==='object'?result.data:null;addComparison(content,data);addDetails(content,data,result?.provenance,result?.evidenceDocumentIds);messages.append(article);messages.scrollTop=messages.scrollHeight}
    function addTyping(){const article=append(messages,'article','message assistant typing');article.id='typing';const inner=append(article,'div','message-inner');addAvatar(inner,'assistant');const answer=append(append(inner,'div','content'),'div','answer');for(let i=0;i<3;i+=1)append(answer,'i','typing-dot');append(answer,'span','typing-label','جارٍ التفكير…');messages.append(article);messages.setAttribute('aria-busy','true');messages.scrollTop=messages.scrollHeight}
    function removeTyping(){document.querySelector('#typing')?.remove();messages.setAttribute('aria-busy','false')}
    function addError(value){const article=append(messages,'article','message assistant error');const inner=append(article,'div','message-inner');addAvatar(inner,'assistant');append(append(inner,'div','content'),'div','answer','حصلت مشكلة أثناء تنفيذ السؤال. '+value);messages.append(article);messages.scrollTop=messages.scrollHeight}
    function resize(){const lines=input.value.split('\\n').length+Math.floor(input.value.length/85);input.rows=Math.max(1,Math.min(5,lines));count.textContent=input.value.length+' / 2000';count.classList.toggle('warn',input.value.length>1800)}
    async function ask(value){const question=value.trim();if(!question||pending)return;pending=true;addUser(question);addTyping();send.disabled=true;input.disabled=true;try{const request={message:question,language:'ar-EG'};if(conversationContext)request.context=conversationContext;const response=await fetch('/api/v1/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const payload=await response.json();if(!response.ok)throw new Error(text(payload?.error?.message,'الخدمة غير متاحة حاليًا.'));removeTyping();addAssistant(payload.result);const nextContext=payload?.result?.data?.conversationContext;conversationContext=nextContext&&typeof nextContext==='object'?nextContext:null}catch(error){removeTyping();addError(error instanceof Error?error.message:'خطأ غير متوقع.')}finally{pending=false;send.disabled=false;input.disabled=false;input.value='';resize();input.focus()}}
    form.addEventListener('submit',event=>{event.preventDefault();ask(input.value)});
    input.addEventListener('input',resize);
    input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit()}});
    document.querySelectorAll('[data-q]').forEach(button=>button.addEventListener('click',()=>ask(button.dataset.q||'')));
    document.querySelector('#newChat').addEventListener('click',()=>location.reload());
    resize();
  </script>
</body>
</html>`;
}
